[package]
name = "xenomai-sys"
version = "0.1.0"
authors = ["Michał Hanusek <mhanusek@energotest.com.pl>"]
edition = "2018"

#[lib]
#name = "xenomai"
#path = "src/lib.rs"

[dependencies]
libc = "0.2.80"
bindgen = "0.56.0"

[build-dependencies]
bindgen = "0.56.0"
cc = "1.0"
pkg-config = "0.3.19"